version: '3'

services:
  neo4j:
    container_name: neo4j_dba
    image: "neo4j:latest"
    volumes:
      - ./data:/data
      - ./import:/var/lib/neo4j/import
    restart: always
    env_file:
      - auth.env
networks:
  default:
    external:
      name: db_network
